version: '3'

networks:
  laravel:

services:
  nginx:
    image: library/nginx:stable-alpine
    container_name: nginx
    ports:
    - "80:80"
    volumes:
    - ./src:/var/www/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./log/nginx:/var/log/nginx
    depends_on:
      - php
      - mysql
    mem_limit: 1024M
    mem_reservation: 512M
    cpus: 4
    networks:
      - laravel

  mysql:
    image: library/mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
    - "4306:3306"
    volumes:
    - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
    - ./src:/var/www/html
    ports:
    - "9000:9000"
    mem_limit: 1024M
    mem_reservation: 512M
    cpus: 4
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    restart: always
    ports:
    - 1025:1025
    - 8025:8025
    networks:
        - laravel

  redis:
    container_name: redis
    image: redis
    ports:
    - 6379:6379
    networks:
      - laravel